### ISSUE TITLE
Admin Pannel

### ISSUE THREAD

**Issue by alfaj7** [alfaj7/SAP-Sultans_056#2]
1. User Management

- [ ]Create User Accounts: Add new users with relevant information (name, email).
- [x]  Edit User Details: Update user information and manage user roles.
- [x] #11

2. Music Library Management

- [x] Add New Music: Upload new songs or albums(title, artist, album, genre, release date).
- [x] Edit Music Details: Update song or album information.
- [x] Delete Music: Remove songs or albums from the library.
- [x] Categorize Music: Organize music into genres, playlists, and other categories.

**Comment by sislam824** [comment]
CRUD operation done with search functionality and applied debouncing
